name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      working-directory: codebase/rdicidr-0.1.0/
      
    steps:
      - uses: actions/setup-node@v3
        with:
    # Version Spec of the version to use in SemVer notation.
    # It also emits such aliases as lts, latest, nightly and canary builds
    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: '15.0.1'
      
      - name: Install dependencies for the agent
        run: |
          npm install -g npm@7
          npm install -g prettier

          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Linter (ESLint)
        run: npm run lint
        working-directory: ${{ env.working-directory }}

      - name: Formatter (Prettier)
        run: npm run prettier
        working-directory: ${{ env.working-directory }}

      - name: Test (Jest)
        run: npm run test --if-present -- --ci
        working-directory: ${{ env.working-directory }}

  build-docker-image:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rdicidr:0.1.0
          context: codebase/rdicidr-0.1.0/
        
  
